add status checks to pr

diff --git a/.github/workflows/tap-pr.yml b/.github/workflows/tap-pr.yml
--- a/.github/workflows/tap-pr.yml
+++ b/.github/workflows/tap-pr.yml
@@ -33,6 +33,37 @@ jobs:
         --data-value-yaml sha=${{ github.event.pull_request.head.sha }} \
         --data-value-yaml branch=${{ github.head_ref }} \
         --data-value-yaml repo=${{ github.repository }} | kubectl apply -f-
+    - name: Get workload name
+      run: echo "FORMATTED_WORKLOAD_NAME=${{ env.REPO_NAME }}-pr-${{ github.event.pull_request.number }}-$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV
+    - name: check status
+      timeout-minutes: 10
+      run: |
+        # Initialize a variable to store the overall status of the conditions
+        OVERALL_STATUS="Unknown"
+        # Loop until the overall status is either True or False
+        while [[ $OVERALL_STATUS == "Unknown" ]]; do
+          # Get the status.conditions of the resource as a JSON array
+          CONDITIONS=$(kubectl -n ${{ env.WORKLOAD_NAMESPACE }} get workload ${{ env.FORMATTED_WORKLOAD_NAME }} -o jsonpath='{.status.conditions}')
+          # Filter the conditions by the name field
+          FILTERED=$(echo $CONDITIONS | jq -c '.[] | select(.name == "source-tester")')
+          # Loop through the filtered array and check each condition
+          for CONDITION in $(echo $FILTERED | jq -c '.[]'); do
+            # Extract the type, status, and message fields
+            TYPE=$(echo $CONDITION | jq -r '.type')
+            STATUS=$(echo $CONDITION | jq -r '.status')
+            MESSAGE=$(echo $CONDITION | jq -r '.message')
+            # If the type is ResourcesHealthy and the status is False, fail the action and print the message
+            if [[ $TYPE == "ResourcesHealthy" && $STATUS == "False" ]]; then
+              echo $MESSAGE
+              exit 1
+            fi
+            # If the status is True, set the overall status to True
+            if [[ $STATUS == "True" ]]; then
+              OVERALL_STATUS="True"
+            fi
+          done
+          sleep 10
+        done
   cleanup:
     if: github.event.action == 'closed'
     runs-on: ubuntu-latest
